Idva6 496 userslist
companieshouse/accounts-association-api pull request #43
Opened 2024-03-15 17:11 UTC by kkonuganti-ch

new feature to fetch associations for user in session

__JIRA Ticket Number__

### Type of change

* [ ] Bug fix
* [ ] New feature
* [ ] Breaking change
* [ ] Infrastructure change

### Pull request checklist

* [ ] I have added unit tests for new code that I have added
* [ ] I have added/updated functional tests where appropriate
* [ ] The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)

__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)__

2024-03-15 17:15 UTC, ch-code-analysis commented
CI: No security warnings found

2024-03-15 17:48 UTC, ch-code-analysis commented
CI: No security warnings found

2024-03-15 18:03 UTC, ch-code-analysis commented
CI: No security warnings found

2024-03-15 18:11 UTC, ch-code-analysis commented
CI: No security warnings found

2024-03-18 11:17 UTC, krishna-patel-ch requested changes

2024-03-18 11:17 UTC, krishna-patel-ch commented on src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
No new tests were added

2024-03-18 11:17 UTC, krishna-patel-ch commented on src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
The tests don't check the response thoroughly enough.

2024-03-18 17:17 UTC, ch-code-analysis commented
CI: No security warnings found

2024-03-18 17:27 UTC, krishna-patel-ch approved these changes

2024-03-18 17:27 UTC, krishna-patel-ch commented on src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
Line 57 change is not addressed

2024-03-18 17:31 UTC, merged